<!DOCTYPE html>
<html class="no-js">
<head>
	<title>What activities are exempt from Corporation Tax? | Business Link</title>
	<?php include $_SERVER['DOCUMENT_ROOT'].'/_inc/meta.php'; ?>
</head>

<body>

<?php include $_SERVER['DOCUMENT_ROOT'].'/_inc/header.php'; ?>

<?php include $_SERVER['DOCUMENT_ROOT'].'/_inc/breadcrumbs.php'; ?>

<div class="row">
	<div class="small-12 large-8 large-push-4 columns">

		
		<h1>Who is liable for Corporation Tax</h1>
		<h2>What activities are exempt from Corporation Tax?</h2>
		<p>HM Revenue &amp; Customs (HMRC) uses the term 'exempt' to refer to certain activities carried out by organisations that are otherwise subject to Corporation Tax requirements.</p>
		<p>These include:</p>
		<ul>
			<li>trading profits generated by charities where those profits arise from - and are applied to - charitable purposes</li>
			<li>profits from any fundraising events run by charities or voluntary organisations provided that those profits are applied to charitable purposes</li>
		</ul>
		<p>HMRC defines charitable purposes as carrying out the primary purpose of the charity and/or directly serving the beneficiaries of the charity.</p>
		<p>Other activities exempt from Corporation Tax include:</p>
		<ul>
			<li>agricultural exhibitions or shows if the agricultural society that's running them uses any profits solely for the purposes of the society</li>
			<li>the sale of permanent health insurance or sickness insurance by a friendly society</li>
			<li>non-commercial activities connected with core health care delivery undertaken by NHS foundation trusts</li>
		</ul>
		<p>
			<a href="/tax-payroll-and-company-information/corporation-tax/charities-and-corporation-tax.php" title="What you need to know about Corporation Tax to help you decide if your charity is liable and has to submit returns">Charities and Corporation Tax</a>
		</p>
		<p>
			<a href="/tax-payroll-and-company-information/corporation-tax/unincorporated-organisations-and-corporation-tax.php" title="Help to decide if your organisation is liable for Corporation Tax, has to submit a Company Tax Return or pay Corporation Tax">Unincorporated organisations and Corporation Tax</a>
		</p>

		<ul>
			<li><a href="/starting-up/corporation-tax/who-is-liable-for-corporation-tax/who-is-not-subject-to-corporation-tax-requirements.php" title="Who is not subject to Corporation Tax requirements?">Prev</a></li>
			<li><a href="detail01ca.html?itemId=1082183519&amp;type=RESOURCES" title="What you must do if your company or organisation is liable for Corporation Tax">Next</a></li>
		</ul>

		<h3>Subjects covered in this guide</h3>
		<ul>
			<li><a href="/tax-payroll-and-company-information/corporation-tax/corporation-tax-for-new-companies-and-organisations/who-is-liable-for-corporation-tax.php" title="Who is liable for Corporation Tax">Introduction</a></li>
			<li><a href="/starting-up/corporation-tax/who-is-liable-for-corporation-tax/who-is-subject-to-corporation-tax-requirements.php">Who is subject to Corporation Tax requirements?</a></li>
			<li><a href="/starting-up/corporation-tax/who-is-liable-for-corporation-tax/who-is-not-subject-to-corporation-tax-requirements.php">Who is not subject to Corporation Tax requirements?</a></li>
			<li>What activities are exempt from Corporation Tax?</li>
			<li><a href="/starting-up/corporation-tax/who-is-liable-for-corporation-tax/what-you-must-do-if-your-company-or-organisation-is-liable-for-corporation-tax.php">What you must do if your company or organisation is liable for Corporation Tax</a></li>
		</ul>

		<?php include $_SERVER['DOCUMENT_ROOT'].'/_inc/print-email.php'; ?>

		<p>Developed with:<br />
			<a href="https://www.gov.uk/government/organisations/hm-revenue-customs" title="HM Revenue &amp; Customs" target="_blank" rel="noopener noreferrer">
				<img src="../../../_img/HMRC_logo.gif" width="134" height="35" alt="" />HM Revenue &amp; Customs
			</a>
		</p>

		<h3>Also on this site</h3>
		<ul>
			<li><a href="/tax-payroll-and-company-information/corporation-tax/charities-and-corporation-tax.php">Charities and Corporation Tax</a></li>
			<li><a href="/tax-payroll-and-company-information/corporation-tax/unincorporated-organisations-and-corporation-tax.php">Unincorporated organisations and Corporation Tax</a></li>
			<li><a href="https://www.gov.uk/browse/tax" target="_blank" rel="noopener noreferrer">Get started with Corporation Tax</a></li>
		</ul>

		<img src="../../../_img/px_startingabusiness.gif" alt="" width="181" height="5" />
		

	</div><!-- // .small-12 large-8 large-push-4 columns -->

	<?php include $_SERVER['DOCUMENT_ROOT'].'/_inc/category-links.php'; ?>

</div><!-- // .row -->

<?php include $_SERVER['DOCUMENT_ROOT'].'/_inc/footer.php'; ?>